# Generated by Django 6.0.3 on 2026-06-21 08:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_district_region_patientprofile_blood_group_and_more'),
        ('appointments', '0011_appointment_diagnosis_appointment_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('chief_complaint', models.TextField(blank=True)),
                ('history_of_present_illness', models.TextField(blank=True)),
                ('physical_examination', models.TextField(blank=True)),
                ('provisional_diagnosis', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='appointments.appointment')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='accounts.doctorprofile')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['-started_at', '-created_at'],
                'indexes': [models.Index(fields=['doctor'], name='consultatio_doctor__6ce364_idx'), models.Index(fields=['patient'], name='consultatio_patient_a5284f_idx'), models.Index(fields=['status'], name='consultatio_status_787364_idx')],
            },
        ),
    ]
