# Generated by Django 6.0.3 on 2026-06-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('appointment_booked', 'Appointment Booked'), ('appointment_approved', 'Appointment Approved'), ('appointment_rejected', 'Appointment Rejected'), ('appointment_rescheduled', 'Appointment Rescheduled'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_reminder', 'Appointment Reminder'), ('payment_success', 'Payment Success'), ('consultation_started', 'Consultation Started'), ('consultation_completed', 'Consultation Completed'), ('diagnosis_added', 'Diagnosis Added'), ('prescription_ready', 'Prescription Ready'), ('lab_requested', 'Lab Requested'), ('lab_result_available', 'Lab Result Available'), ('invoice_issued', 'Invoice Issued'), ('dispensing_ready', 'Dispensing Ready'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
