# Generated by Django 6.0.3 on 2026-04-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_remove_appointment_patient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="fee",
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
    ]
