# Generated by Django 6.0.3 on 2026-04-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_preferred_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
