# Generated by Django 6.0.3 on 2026-05-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointment_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='preferred_date_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='preferred_date_3',
            field=models.DateField(blank=True, null=True),
        ),
    ]
