# Generated by Django 6.0.3 on 2026-05-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_appointment_preferred_date_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
