# Generated by Django 6.0.3 on 2026-06-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_id',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
