# Generated by Django 6.0.3 on 2026-07-04 08:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def migrate_legacy_statuses(apps, schema_editor):
    Appointment = apps.get_model("appointments", "Appointment")
    AppointmentLog = apps.get_model("appointments", "AppointmentLog")
    status_map = {
        "accepted": "confirmed",
        "declined": "cancelled",
        "expired": "no_show",
    }
    for old_status, new_status in status_map.items():
        Appointment.objects.filter(status=old_status).update(status=new_status)
        AppointmentLog.objects.filter(old_status=old_status).update(
            old_status=new_status
        )
        AppointmentLog.objects.filter(new_status=old_status).update(
            new_status=new_status
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_doctoravailability_options_and_more'),
        ('appointments', '0013_appointment_appointment_id'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('waiting_in_queue', 'Waiting in Queue'), ('in_consultation', 'In Consultation'), ('waiting_for_laboratory', 'Waiting for Laboratory'), ('laboratory_in_progress', 'Laboratory In Progress'), ('laboratory_results_ready', 'Laboratory Results Ready'), ('back_to_doctor', 'Back to Doctor'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed')], default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='appointmentlog',
            name='new_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentlog',
            name='old_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='AppointmentQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('queue_date', models.DateField()),
                ('queue_number', models.PositiveIntegerField()),
                ('checked_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='accounts.doctorprofile')),
            ],
            options={
                'ordering': ['queue_date', 'doctor', 'queue_number'],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'queue_date', 'queue_number'), name='unique_doctor_daily_queue_number')],
            },
        ),
    ]
