# Generated by Django 6.0.3 on 2026-07-27 13:55

from django.db import migrations


def migrate_completed_to_success(apps, schema_editor):
    Payment = apps.get_model("appointments", "Payment")
    Payment.objects.filter(status="completed").update(status="success")


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0015_update_payment_statuses"),
    ]

    operations = [
        migrations.RunPython(migrate_completed_to_success, reverse_code=migrations.RunPython.noop),
    ]
