# Generated by Django 6.0.3 on 2026-04-02 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('appointments', '0002_illnesscategory_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.illnesscategory'),
        ),
        migrations.DeleteModel(
            name='IllnessCategory',
        ),
    ]
