# Generated by Django 6.0.3 on 2026-04-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clinicsettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClinicSettings',
            new_name='SystemSettings',
        ),
    ]
