# Generated by Django 6.0.3 on 2026-04-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_clinicsettings_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='appointment_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
