# Generated by Django 6.0.3 on 2026-06-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_district_region_patientprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other'), ('Prefer not to say', 'prefer not to say')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('lab_tech', 'Lab Technician'), ('receptionist', 'Receptionist'), ('patient', 'Patient')], default='patient', max_length=20),
        ),
    ]
