# Generated by Django 6.0.3 on 2026-06-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_patientprofile_gender_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='patient_id',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
