# Generated by Django 6.0.3 on 2026-07-09 14:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_set_default_appointment_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='appointment_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10),
        ),
    ]
