import io
from django.utils import timezone
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from api.appointments.models import Appointment
from api.laboratory.models import LabRequestItem
from .models import User

def fetch_report_data(user):
    data = {"role": user.role, "full_name": user.full_name}
    today = timezone.localdate()
    
    if user.role in [User.Role.ADMIN, User.Role.RECEPTIONIST]:
        data["title"] = "General System Report"
        data["stats"] = {
            "Total Appointments Today": Appointment.objects.filter(appointment_date=today).count(),
            "Pending Appointments": Appointment.objects.filter(status=Appointment.Status.PENDING).count(),
            "Completed Appointments": Appointment.objects.filter(status=Appointment.Status.COMPLETED).count(),
        }
        recent = Appointment.objects.order_by("-created_at")[:10]
        data["recent_activities"] = [
            ["Date", "Patient", "Doctor", "Status"],
            *[[a.appointment_date.strftime("%Y-%m-%d"), a.patient.user.full_name if a.patient else "-", a.doctor.user.full_name if a.doctor else "-", a.status] for a in recent]
        ]
        
    elif user.role == User.Role.DOCTOR:
        data["title"] = "Doctor Activities Report"
        my_appointments = Appointment.objects.filter(doctor__user=user)
        data["stats"] = {
            "My Appointments Today": my_appointments.filter(appointment_date=today).count(),
            "My Pending Appointments": my_appointments.filter(status=Appointment.Status.PENDING).count(),
            "My Completed Appointments": my_appointments.filter(status=Appointment.Status.COMPLETED).count(),
        }
        recent = my_appointments.order_by("-created_at")[:10]
        data["recent_activities"] = [
            ["Date", "Patient", "Status", "Payment"],
            *[[a.appointment_date.strftime("%Y-%m-%d"), a.patient.user.full_name if a.patient else "-", a.status, a.payment_status] for a in recent]
        ]
        
    elif user.role == User.Role.LAB_TECH:
        data["title"] = "Lab Technician Activities Report"
        # LabTech doesn't have a direct relation in LabRequest unless verified_by in LabResult
        from api.laboratory.models import LabResult
        my_results = LabResult.objects.filter(verified_by=user)
        data["stats"] = {
            "Tests Verified Today": my_results.filter(created_at__date=today).count(),
            "Total Tests Verified": my_results.count(),
        }
        recent = my_results.order_by("-created_at")[:10]
        data["recent_activities"] = [
            ["Date", "Test", "Patient", "Result"],
            *[[r.created_at.strftime("%Y-%m-%d"), r.request_item.test_type.name, r.request_item.lab_request.patient.user.full_name if r.request_item.lab_request.patient else "-", r.result] for r in recent]
        ]
    else:
        data["title"] = "User Report"
        data["stats"] = {}
        data["recent_activities"] = []
        
    return data


def generate_general_docx_report(user):
    doc = Document()
    data = fetch_report_data(user)

    heading = doc.add_heading(data["title"], 0)
    heading.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph(f"Report Generated: {timezone.now().strftime('%Y-%m-%d %H:%M')}")
    doc.add_paragraph(f"Generated By: {data['full_name']} ({data['role'].upper()})")
    doc.add_paragraph("")

    doc.add_heading('Summary Statistics', level=2)
    for k, v in data["stats"].items():
        doc.add_paragraph(f"{k}: {v}")

    doc.add_paragraph("")
    doc.add_heading('Recent Activities', level=2)
    
    if len(data["recent_activities"]) <= 1:
        doc.add_paragraph("No recent activities found.")
    else:
        table_data = data["recent_activities"]
        table = doc.add_table(rows=len(table_data), cols=len(table_data[0]))
        table.style = 'Table Grid'
        
        for i, row in enumerate(table_data):
            for j, cell_val in enumerate(row):
                cell = table.cell(i, j)
                cell.text = str(cell_val)
                if i == 0:
                    for paragraph in cell.paragraphs:
                        for run in paragraph.runs:
                            run.bold = True

    doc.add_paragraph("\n\nThis is an electronically generated report.")
    
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer


def generate_general_pdf_report(user):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    elements = []
    
    styles = getSampleStyleSheet()
    title_style = styles['Heading1']
    title_style.alignment = 1 # Center
    details_style = styles['Normal']
    
    data = fetch_report_data(user)
    
    elements.append(Paragraph(data["title"], title_style))
    elements.append(Spacer(1, 12))
    elements.append(Paragraph(f"<b>Generated:</b> {timezone.now().strftime('%Y-%m-%d %H:%M')}", details_style))
    elements.append(Paragraph(f"<b>Generated By:</b> {data['full_name']} ({data['role'].upper()})", details_style))
    elements.append(Spacer(1, 12))
    
    elements.append(Paragraph("<b>Summary Statistics</b>", styles['Heading2']))
    for k, v in data["stats"].items():
        elements.append(Paragraph(f"• {k}: <b>{v}</b>", details_style))
    elements.append(Spacer(1, 12))
    
    elements.append(Paragraph("<b>Recent Activities</b>", styles['Heading2']))
    if len(data["recent_activities"]) <= 1:
        elements.append(Paragraph("No recent activities found.", details_style))
    else:
        # Convert header row to bold
        table_data = []
        for i, row in enumerate(data["recent_activities"]):
            if i == 0:
                table_data.append([Paragraph(f"<b>{cell}</b>", details_style) for cell in row])
            else:
                table_data.append([Paragraph(str(cell), details_style) for cell in row])
                
        table = Table(table_data)
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f3f4f6')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.white),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#e5e7eb')),
        ]))
        elements.append(table)
        
    elements.append(Spacer(1, 30))
    elements.append(Paragraph("<i>This is an electronically generated report.</i>", details_style))
    
    doc.build(elements)
    buffer.seek(0)
    return buffer
