# Generated by Django 6.0.3 on 2026-06-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtesttype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
