# Generated by Django 6.0.3 on 2026-07-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_remove_labtesttype_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
