# Generated by Django 6.0.3 on 2026-07-27 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0015_update_payment_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_payload', models.JSONField()),
                ('headers', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('processing_result', models.CharField(max_length=32)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_audits', to='appointments.payment')),
            ],
            options={
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['payment', 'processed_at'], name='payments_we_payment_9189e3_idx')],
            },
        ),
    ]
