# Generated by Django 6.0.3 on 2026-06-21 08:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_district_region_patientprofile_blood_group_and_more'),
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('allergies', models.TextField(blank=True)),
                ('chronic_conditions', models.TextField(blank=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['patient__user__last_name', 'patient__user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('disease_name', models.CharField(max_length=255)),
                ('icd10_code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('provisional', 'Provisional'), ('final', 'Final')], default='provisional', max_length=20)),
                ('diagnosed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='consultations.consultation')),
            ],
            options={
                'ordering': ['-diagnosed_at', '-created_at'],
                'indexes': [models.Index(fields=['consultation'], name='medical_rec_consult_8bb8dc_idx'), models.Index(fields=['type'], name='medical_rec_type_935ada_idx'), models.Index(fields=['disease_name'], name='medical_rec_disease_5bc6d5_idx')],
            },
        ),
    ]
