# Generated by Django 6.0.3 on 2026-07-18 03:47

import api.health_education.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_education', '0002_educationalcontent_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalcontent',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='health_education/images/', validators=[api.health_education.models.validate_media_size, api.health_education.models.validate_media_content_type]),
        ),
        migrations.AlterField(
            model_name='educationalcontent',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='health_education/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm', 'm4v']), api.health_education.models.validate_media_size, api.health_education.models.validate_media_content_type]),
        ),
    ]
